//! This is a generated file - DO NOT EDIT!

const std = @import("std");
const avro = @import("zig-avro");

id: []const u8,
masterId: ?[]const u8 = null,
name: []const u8,
sportType: SportType = .UNKNOWN,
sportId: []const u8,
round: ?Round = null,
tournamentTemplate: ?TournamentTemplateProjection = null,
tournament: ?TournamentProjection = null,
tournamentStage: TournamentStageProjection,
venue: ?Venue = null,
venueId: ?[]const u8 = null,
venueNeutralGround: bool,
priority: i32,
platforms: avro.Array([]const u8),
startDate: ?i32 = null,
startDateTime: ?i64 = null,
status: EventStatus = .UNKNOWN,
statusDescription: EventStatusDescription = .UNKNOWN,
images: avro.Array(Image) = .{},
programs: avro.Array(ProgramInfo) = .{},
participants: avro.Array(EventParticipantsParticipant) = .{},
deleted: bool,
properties: avro.Map([]const u8) = .{},
const ProgramInfo = struct {
    assetId: ?[]const u8 = null,
    assetDuration: ?[]const u8 = null,
    channelName: ?[]const u8 = null,
    gpid: ?[]const u8 = null,
    airTime: ?i64 = null,
    live: bool,
    channel: Channel = .UNKNOWN,
    channels: avro.Array(Channel) = .{},
};
const EventLargeProjection = struct {
    id: []const u8,
    masterId: ?[]const u8 = null,
    name: []const u8,
    sportType: SportType = .UNKNOWN,
    sportId: []const u8,
    round: ?Round = null,
    tournamentTemplate: ?TournamentTemplateProjection = null,
    tournament: ?TournamentProjection = null,
    tournamentStage: TournamentStageProjection,
    venue: ?Venue = null,
    venueId: ?[]const u8 = null,
    venueNeutralGround: bool,
    priority: i32,
    platforms: avro.Array([]const u8),
    startDate: ?i32 = null,
    startDateTime: ?i64 = null,
    status: EventStatus = .UNKNOWN,
    statusDescription: EventStatusDescription = .UNKNOWN,
    images: avro.Array(Image) = .{},
    programs: avro.Array(ProgramInfo) = .{},
    participants: avro.Array(EventParticipantsParticipant) = .{},
    deleted: bool,
    properties: avro.Map([]const u8) = .{},
};
const ImageType = enum {
    ICON,
    ICON_WITH_TEXT,
    ICON_WITH_SHORT_TEXT,
    PROFILE,
    PROFILE_MOUNTAIN,
    MAP,
    UNKNOWN,
};
const Gender = enum {
    MALE,
    FEMALE,
    UNDEFINED,
    MIXED,
};
const Venue = struct {
    id: []const u8,
    masterId: ?[]const u8 = null,
    name: []const u8,
    countryId: ?[]const u8 = null,
    images: avro.Array(Image) = .{},
    deleted: bool,
    properties: avro.Map([]const u8) = .{},
};
const PlatformType = enum {
    WEB,
    APP,
    TV,
    UNKNOWN,
};
const EventParticipantsParticipant = struct {
    id: []const u8,
    number: i32,
    participant: ParticipantProjection,
    lineupConfirmed: bool = false,
    results: avro.Array(Result) = .{},
    properties: avro.Map([]const u8) = .{},
};
const ParticipantProjection = struct {
    id: []const u8,
    masterId: ?[]const u8 = null,
    name: []const u8,
    gender: Gender = "UNDEFINED",
    type: ParticipantType = .UNDEFINED,
    country: ?ParticipantCountry = null,
    images: avro.Array(Image) = .{},
    toBeDecided: bool,
    deleted: bool,
    properties: avro.Map([]const u8) = .{},
};
const ResultType = enum {
    ORDINARY_TIME,
    EXTRA_TIME,
    PENALTY_SHOOTOUT,
    FINAL_RESULT,
    HALFTIME,
    RUNNING_SCORE,
    STROKES_1ST_ROUND,
    STROKES_2ND_ROUND,
    STROKES_3RD_ROUND,
    STROKES_4TH_ROUND,
    STROKES_5TH_ROUND,
    PAR,
    POSITION,
    MADE_CUT,
    MATCH_PLAY_SCORE,
    WEIGHT,
    PERIOD_1,
    PERIOD_2,
    PERIOD_3,
    PENALTY_SHOOTOUT_DEPRECATED,
    QUARTER_1,
    QUARTER_2,
    QUARTER_3,
    QUARTER_4,
    SET_1,
    SET_2,
    SET_3,
    SET_4,
    SET_5,
    WON_SETS,
    TIEBREAK_1,
    TIEBREAK_2,
    TIEBREAK_3,
    TIEBREAK_4,
    TIEBREAK_5,
    GAME_SCORE,
    SET_6,
    SET_7,
    RANK,
    DURATION,
    POINTS,
    DISTANCE,
    COMMENT,
    LAPS,
    LAPS_BEHIND,
    PITSTOPS,
    INNING_1,
    INNING_2,
    INNING_3,
    INNING_4,
    INNING_5,
    INNING_6,
    INNING_7,
    INNING_8,
    INNING_9,
    EXTRA_INNING,
    HITS,
    ERRORS,
    MISSES,
    HORSE_RACING_ODDS,
    STARTNUMBER,
    MEDAL,
    MISSED_SHOTS,
    ADDITIONAL_SHOTS,
    TRIES,
    FOUR_4S_POINTS,
    SIX_6S_POINTS,
    OVERS,
    EXTRAS,
    WICKETS,
    SECOND_POINTS,
    SECOND_OVERS,
    SECOND_EXTRA,
    SECOND_WICKETS,
    SPEED,
    JUMP_OFF_PENALTIES,
    JUMP_OFF_TIME,
    NET_POINTS,
    DRAWNUMBER,
    OFFICIAL_RATING,
    FORM,
    AGE,
    FASTEST_LAP_POINT,
    HANDICAP,
    PLACE_WIN,
    ALLOWANCE,
    STROKES_POINTS_1ST_ROUND,
    STROKES_POINTS_2ND_ROUND,
    STROKES_POINTS_3RD_ROUND,
    STROKES_POINTS_4TH_ROUND,
    STROKES_POINTS_5TH_ROUND,
    WINS,
    RIDES,
    BEST_TIME,
    UNKNOWN,
};
const TournamentProjection = struct {
    id: []const u8,
    masterId: ?[]const u8 = null,
    name: []const u8,
    sportType: SportType = "UNKNOWN",
    sportId: []const u8,
    tournamentTemplateId: []const u8,
    startDate: ?i64 = null,
    endDate: ?i64 = null,
    priority: i32,
    platforms: avro.Array([]const u8),
    images: avro.Array(Image) = .{},
    active: bool,
    deleted: bool,
    properties: avro.Map([]const u8) = .{},
};
const EventStatusDescription = enum {
    PLAYOFF_INTERRUPTED,
    ONE_OF_SIXTEENTH_ROUND_STARTED,
    ONE_OF_THIRTY_SECOND_ROUND_STARTED,
    ONE_OF_EIGHTH_ROUND_STARTED,
    FIRST_GAME_FINISHED,
    FIRST_GAME_STARTED,
    FIRST_INNING_FINISHED,
    FIRST_INNING_STARTED,
    FIRST_MAP_FINISHED,
    FIRST_MAP_STARTED,
    FIRST_PERIOD,
    FIRST_QUARTER,
    FIRST_QUARTER_FINISHED,
    FIRST_ROUND_FINISHED,
    FIRST_ROUND_INTERRUPTED,
    FIRST_ROUND_POSTPONED,
    FIRST_ROUND_STARTED,
    FIRST_SET,
    FIRST_HALF,
    SECOND_GAME_FINISHED,
    SECOND_GAME_STARTED,
    SECOND_INNING_STARTED,
    SECOND_MAP_FINISHED,
    SECOND_MAP_STARTED,
    SECOND_PERIOD,
    SECOND_QUARTER,
    SECOND_ROUND_FINISHED,
    SECOND_ROUND_INTERRUPTED,
    SECOND_ROUND_POSTPONED,
    SECOND_ROUND_STARTED,
    SECOND_SET,
    SECOND_HALF,
    THIRD_GAME_FINISHED,
    THIRD_GAME_STARTED,
    THIRD_MAP_FINISHED,
    THIRD_MAP_STARTED,
    THIRD_PERIOD,
    THIRD_QUARTER,
    THIRD_QUARTER_FINISHED,
    THIRD_ROUND_FINISHED,
    THIRD_ROUND_INTERRUPTED,
    THIRD_ROUND_POSTPONED,
    THIRD_ROUND_STARTED,
    THIRD_SET,
    FOURTH_GAME_FINISHED,
    FOURTH_GAME_STARTED,
    FOURTH_MAP_FINISHED,
    FOURTH_MAP_STARTED,
    FOURTH_QUARTER,
    FOURTH_ROUND_FINISHED,
    FOURTH_ROUND_INTERRUPTED,
    FOURTH_ROUND_POSTPONED,
    FOURTH_ROUND_STARTED,
    FOURTH_SET,
    FIFTH_GAME_STARTED,
    FIFTH_MAP_STARTED,
    FIFTH_ROUND_FINISHED,
    FIFTH_ROUND_INTERRUPTED,
    FIFTH_ROUND_POSTPONED,
    FIFTH_ROUND_STARTED,
    FIFTH_SET,
    SIXTH_ROUND_FINISHED,
    SIXTH_ROUND_INTERRUPTED,
    SIXTH_ROUND_POSTPONED,
    SIXTH_ROUND_STARTED,
    ABANDONED,
    ACTIVE,
    AWAITING_INFO,
    AWAITING_START,
    BOTTOM_FIRST,
    BOTTOM_SECOND,
    BOTTOM_THIRD,
    BOTTOM_FOURTH,
    BOTTOM_FIFTH,
    BOTTOM_SIXTH,
    BOTTOM_7TH,
    BOTTOM_8TH,
    BOTTOM_9TH,
    BOTTOM_EI,
    CANCELLED,
    CANCELLED_DRAW,
    INACTIVE,
    DELETED,
    DINNER_BREAK,
    END_FIRST,
    END_SECOND,
    END_THIRD,
    END_FOURTH,
    END_FIFTH,
    END_SIXTH,
    END_7TH,
    END_8TH,
    END_9TH,
    EXCLUDED,
    EXTRA_TIME,
    EXTRA_TIME_FIRST_HALF,
    FIRST_EXTRA_TIME_PERIOD,
    EXTRA_TIME_FIRST_HALF_SECOND_TIME,
    SECOND_EXTRA_TIME_PERIOD,
    EXTRA_TIME_SECOND_HALF,
    EXTRA_TIME_SECOND_HALF_SECOND_TIME,
    EXTRA_TIME_END_OF_FIRST_HALF,
    THIRD_EXTRA_TIME_PERIOD,
    FOURTH_EXTRA_TIME_PERIOD,
    FIFTH_EXTRA_TIME_PERIOD,
    SIXTH_EXTRA_TIME_PERIOD,
    SEVENTH_EXTRA_TIME_PERIOD,
    EIGTH_EXTRA_TIME_PERIOD,
    FINAL_ROUND_STARTED,
    FINISHED,
    FINISHED_AEI,
    FINISHED_AET,
    FINISHED_AGG,
    FINISHED_AGP,
    FINISHED_AGS,
    FINISHED_AP,
    FINISHED_ASD,
    FINISHED_ASG,
    FINISHED_OT,
    FINISHED_AFTER_AWARDED_WIN,
    FINISHED_AFTER_OVERTIME,
    FINISHED_AFTER_PLAYOFF,
    GOLDEN_GOAL_FIRST_HALF,
    GOLDEN_GOAL_SECOND_HALF,
    HALFTIME,
    HALVED,
    INTERRUPTED,
    KICK_OFF_DELAYED,
    LUNCH_BREAK,
    NOT_AVAILABLE,
    NO_INFO_YET,
    NOT_STARTED,
    OVERTIME,
    OVERTIME_FIRST_HALF,
    OVERTIME_SECOND_HALF,
    PAUSE,
    PENALTY,
    PICK_BAN,
    PLAYOFF_POSTPONED,
    PLAYOFF_STARTED,
    POSTPONED,
    QUARTERFINAL_ROUND_STARTED,
    SEMIFINAL_ROUND_STARTED,
    SILVER_GOAL_FIRST_HALF,
    SILVER_GOAL_SECOND_HALF,
    START_DELAYED,
    STARTED,
    STUMPS_DAY_1,
    STUMPS_DAY_2,
    STUMPS_DAY_3,
    STUMPS_DAY_4,
    STUMPS_DAY_5,
    SUDDEN_DEATH,
    TIMEOUT_AWAY_TEAM,
    TIMEOUT_HOME_TEAM,
    TO_FINISH,
    TOP_FIRST,
    TOP_SECOND,
    TOP_THIRD,
    TOP_FOURTH,
    TOP_FIFTH,
    TOP_SIXTH,
    TOP_7TH,
    TOP_8TH,
    TOP_9TH,
    TOP_EI,
    WAITING_FOR_OVERTIME,
    WAITING_FOR_PENALTY,
    WAITING_FOR_SILVER_GOAL,
    WAITING_FOR_EXTRA_TIME,
    WAITING_FOR_GOLDEN_GOAL,
    WITHDRAWN,
    UNKNOWN,
};
const TournamentTemplateProjection = struct {
    id: []const u8,
    masterId: ?[]const u8 = null,
    sportType: SportType = "UNKNOWN",
    sportId: []const u8,
    name: []const u8,
    gender: Gender = .UNDEFINED,
    priority: i32,
    platforms: avro.Array([]const u8) = .{},
    images: avro.Array(Image) = .{},
    deleted: bool,
    properties: avro.Map([]const u8) = .{},
};
const EventStatus = enum {
    INTERRUPTED,
    NOT_STARTED,
    CANCELLED,
    DELETED,
    FINISHED,
    UNKNOWN,
    IN_PROGRESS,
};
const Channel = enum {
    TV2,
    TV2_SPORT_PREMIUM,
    TV2_SPORT_PREMIUM_2,
    TV2_SPORT_1,
    TV2_SPORT_2,
    TV2_ZEBRA,
    TV2_SUMO,
    TV2_PLAY,
    TV2_LIVE,
    UNKNOWN,
};
const ParticipantCountry = struct {
    id: []const u8,
    name: []const u8,
    images: avro.Array(Image),
};
const Result = struct {
    value: ?[]const u8,
    resultType: ResultType = .UNKNOWN,
};
const SportType = enum {
    FOOTBALL,
    HANDBALL,
    ICE_HOCKEY,
    CYCLING,
    CHESS,
    VOLLEYBALL,
    BASKETBALL,
    FLOORBALL,
    ALPINE,
    NORDIC_COMBINED,
    CROSS_COUNTRY,
    SKI_JUMPING,
    BIATHLON,
    SHORT_TRACK_SPEED_SKATING,
    SKELETON,
    FREESTYLE_SKIING,
    SNOWBOARDING,
    BOBSLEIGH,
    FIGURE_SKATING,
    CURLING,
    CROSS_COUNTRY_SKIING,
    SPEED_SKATING,
    HARNESS_RACING,
    TENNIS,
    BADMINTON,
    ATHLETICS,
    FUNCTIONAL_FITNESS_AND_CROSSFIT,
    GYMNASTICS,
    MARTIAL_ARTS_BOXING,
    MARTIAL_ARTS_KARATE,
    MARTIAL_ARTS_MMA,
    MOTORSPORT,
    MOTORSPORT_BILCROSS,
    MOTORSPORT_CROSSCART,
    MOTORSPORT_DRAGRACE,
    MOTORSPORT_MOTOSPORT,
    MOTORSPORT_QUADCROSS,
    MOTORSPORT_RADIO,
    MOTORSPORT_RALLYCROSS,
    MOTORSPORT_ROADRACING,
    MOTORSPORT_SNOWSCOOTER,
    MOTORSPORT_TRIAL,
    PADEL,
    SWIMMING,
    OTHER,
    UNKNOWN,
};
const TournamentStageProjection = struct {
    id: []const u8,
    masterId: ?[]const u8 = null,
    name: []const u8,
    sportType: SportType = "UNKNOWN",
    sportId: []const u8,
    tournamentTemplateId: []const u8,
    tournamentId: []const u8,
    gender: Gender = "UNDEFINED",
    countryId: ?[]const u8 = null,
    startDate: ?i64 = null,
    endDate: ?i64 = null,
    priority: i32,
    platforms: avro.Array([]const u8) = .{},
    images: avro.Array(Image) = .{},
    active: bool,
    deleted: bool,
    properties: avro.Map([]const u8) = .{},
};
const Image = struct {
    type: ImageType = .UNKNOWN,
    url: []const u8,
    inverted: bool,
    width: ?i32 = null,
    height: ?i32 = null,
    platform: PlatformType = .UNKNOWN,
    properties: avro.Map([]const u8) = .{},
};
const ParticipantType = enum {
    ATHLETE,
    TEAM,
    ORGANIZATION,
    MANAGER,
    ASSISTANT_MANAGER,
    COACH,
    ASSISTANT_COACH,
    OFFICIAL,
    HORSE,
    UNDEFINED,
};
const Round = struct {
    number: ?i32 = null,
    name: []const u8,
};
